#cloud-config
package_update: true
package_upgrade: true

packages:
  - nfs-common

runcmd:
  # Create mount point
  - mkdir -p /mnt/${volume_name}
  
  # Mount the NFS volume
  - mount -t nfs -o vers=3 ${volume_ip}:/${volume_name} /mnt/${volume_name}
  
  # Add to fstab for persistent mounting
  - echo "${volume_ip}:/${volume_name} /mnt/${volume_name} nfs rw,hard,rsize=65536,wsize=65536,vers=3,tcp 0 0" >> /etc/fstab
  
  # Create VM-specific directory
  - mkdir -p /mnt/${volume_name}/vm-${vm_index}
  
  # Create a test file to verify the mount
  - echo "VM ${vm_index} - NFS volume mounted successfully at $(date)" > /mnt/${volume_name}/vm-${vm_index}/mount-test.txt
  
  # Set permissions
  - chmod 755 /mnt/${volume_name}
  - chmod 755 /mnt/${volume_name}/vm-${vm_index}
  
  # Create a shared directory for collaboration
  - mkdir -p /mnt/${volume_name}/shared
  - chmod 777 /mnt/${volume_name}/shared

final_message: "VM ${vm_index} - NFS volume has been mounted successfully" 